services:
  - type: static
    name: my-static-site
    repo: https://github.com/yourusername/your-repo
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: build
    plan: free
